# network configuration capabilities, write a file
# /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg with the following:
# network: {config: disabled}
#network:
#    ethernets:
#        eth0:
#            dhcp4: true
#            optional: true
#    version: 2
#
#50-cloud-init.yaml
network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      addresses:
      - 192.168.0.30/24
      routes:
      - to: default
        via: 192.168.0.1
      nameservers:
        addresses: [192.168.0.1, 8.8.8.8]
