---
- name: kubeadm to hosts Install and Configure
  hosts: pihosts
  gather_facts: false
  become: true
  tasks:
    - name: Execute the swapoff command over Command module
      command: swapoff -a 
    #- name: Execute the nc command over Command module
    #  raw: nc 127.0.0.1 6443
    #Prerequisites to CRI containerd
    - name: prerequisites to CRI containerd
      shell: |
        cat <<EOF | tee /etc/modules-load.d/k8s.conf overlay br_netfilter EOF
    - name: Execute the modprobe overlay command over Command module
      command: modprobe overlay
    - name: Execute the modprobe br_netfilter command over Command module
      shell: | 
        modprobe br_netfilter
    - name: Sysctl params required by setup, params persist across reboots
      shell: | 
        cat <<EOF | tee /etc/sysctl.d/k8s.conf
                    net.bridge.bridge-nf-call-iptables  = 1
                    net.bridge.bridge-nf-call-ip6tables = 1
                    net.ipv4.ip_forward                 = 1
                    EOF
    - name: Apply sysctl params without reboot
      command: sysctl --system
    #Update
    - name: update the apt package index i.e. apt-get update
      apt: update_cache=yes
    #Install Containerd
    - name: Install containerd
      apt:
        name: containerd
        state: present
    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /etc/containerd
        state: directory
        mode: '0755'
    - name: Generate containerd config 
      shell: | 
        containerd config default | tee /etc/containerd/config.toml
    - name: Change SystemdCgroup = true on config.toml
      lineinfile:
        path: /etc/containerd/config.toml
        regexp: '(^            SystemdCgroup = )'
        line: '            SystemdCgroup = true'
    - name: Restart containerd
      command: systemctl restart containerd
    #Kubernetes Cluster Prerequisites
    - name: Install apt-transport-https
      command: sudo apt install -y wget curl gnupg2 software-properties-common apt-transport-https ca-certificates
    #Add Repos and keyrings
    - name: Download the Google Cloud public signing key
      raw: |
        sudo curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    - name: Add the Kubernetes apt repository
      raw: | 
        echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list

    #Update
    - name: update the apt package index i.e. apt-get update
      apt: update_cache=yes

    #Control Plane and lock to version latest v.1.27.0  
    - name: Install kubelet, kubeadm, and kubectl (specific versions)
      package:
        name:
        - kubelet=1.27.0-00   # Specify the desired version
        - kubeadm=1.27.0-00   # Specify the desired version
        - kubectl=1.27.0-00   # Specify the desired version
        state: present

    - name:
      command: apt-mark hold kubelet kubeadm kubectl
